version: 2
workflows:
  version: 2
  test:
    jobs:
    - test_crystal_nightly
jobs:
  test_crystal_nightly:
    docker:
    - image: 'crystallang/crystal:nightly'
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - 'v1-dependencies-{{ checksum "shard.yml" }}'
        - v1-dependencies-
    - run: shards
    - save_cache:
        paths:
        - lib
        key: 'v1-dependencies-{{ checksum "shard.yml" }}'
    - run: bin/test
